[package]
name = "mimedb"
version = "0.1.0"
edition = "2021"
license = "GPLv2+"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "^0.3"
