[package]
name = "shared-mime"
version = "0.1.0"
edition = "2021"
license = "GPLv2+"

[dependencies]
thiserror = "^1.0"
log = "^0.4"
serde = { version = "^1.0", features = ["derive"] }

# parser dependencies
quick-xml = { version = "^0.35", features = ["serialize"], optional = true }

serde_json = { version = "^1.0", optional = true }

# support for CLI tools
clap = { version = "^4.5", features = ["derive"], optional = true }
stderrlog = { version = "^0.6", optional = true }
anyhow = { version = "^1", optional = true }

[features]
default = ["xdg-runtime"]
json = ["serde_json"]
xdg-runtime = ["quick-xml"]
cli = ["clap", "stderrlog", "anyhow", "xdg-runtime", "json"]

[[bin]]
name = "shared-mime-rs"
path = "src/main.rs"
required-features = ["cli"]
