[package]
name = "shared-mime"
version = "0.1.0"
edition = "2021"
license = "GPLv2+"

[dependencies]
thiserror = "^1.0"
serde = { version = "^1.0", features = ["derive"] }

# parser dependencies
quick-xml = { version = "^0.35", features = ["serialize"], optional = true }

# support for CLI tools
clap = { version = "^4.5", features = ["derive"], optional = true }

[features]
default = ["xdg-runtime"]
xdg-runtime = ["quick-xml"]
cli = ["clap", "xdg-runtime"]

[[bin]]
name = "shared-mime-rs-test-parse"
required-features = ["cli"]
