[package]
name = "shared-mime-embedded"
version = "0.1.0"
edition = "2021"
license = "GPLv2+"

[dependencies]
shared-mime = { version = "0.1.0", workspace = true, default-features = false }

[features]
xdg-runtime = ["shared-mime/xdg-runtime"]

[build-dependencies]
shared-mime = { version = "0.1.0", workspace = true, features = [
  "xdg-runtime",
] }
