[package]
name = "shared-mime-embedded"
version = "0.1.0"
edition = "2021"
license = "GPLv2+"

[dependencies]
shared-mime = { version = "0.1.0", default-features = false, path = "../shared-mime" }

[features]
xdg-runtime = ["shared-mime/xdg-runtime"]

[build-dependencies]
anyhow = "^1.0"
postcard = { version = "^1.0", features = ["use-std"] }
shared-mime = { version = "0.1.0", path = "../shared-mime", features = [
  "xdg-runtime",
] }
